services:
  postgres: 
    container_name: blog_api
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports: 
      - 5435:5432